/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as BookingsReceivedRouteImport } from './routes/bookings-received'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenueVenueIdRouteImport } from './routes/venue.$venueId'
import { Route as VendorVenuesRouteImport } from './routes/vendor.venues'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as ActivityActivityRouteImport } from './routes/activity.$activity'
import { Route as VenueVenueIdCourtsRouteImport } from './routes/venue.$venueId.courts'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsReceivedRoute = BookingsReceivedRouteImport.update({
  id: '/bookings-received',
  path: '/bookings-received',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueVenueIdRoute = VenueVenueIdRouteImport.update({
  id: '/venue/$venueId',
  path: '/venue/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVenuesRoute = VendorVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VendorRoute,
} as any)
const ActivityActivityRoute = ActivityActivityRouteImport.update({
  id: '/activity/$activity',
  path: '/activity/$activity',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueVenueIdCourtsRoute = VenueVenueIdCourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => VenueVenueIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/bookings-received': typeof BookingsReceivedRoute
  '/confirmation': typeof ConfirmationRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/vendor': typeof VendorRouteWithChildren
  '/activity/$activity': typeof ActivityActivityRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/venues': typeof VendorVenuesRoute
  '/venue/$venueId': typeof VenueVenueIdRouteWithChildren
  '/venue/$venueId/courts': typeof VenueVenueIdCourtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/bookings-received': typeof BookingsReceivedRoute
  '/confirmation': typeof ConfirmationRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/vendor': typeof VendorRouteWithChildren
  '/activity/$activity': typeof ActivityActivityRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/venues': typeof VendorVenuesRoute
  '/venue/$venueId': typeof VenueVenueIdRouteWithChildren
  '/venue/$venueId/courts': typeof VenueVenueIdCourtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/bookings-received': typeof BookingsReceivedRoute
  '/confirmation': typeof ConfirmationRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/vendor': typeof VendorRouteWithChildren
  '/activity/$activity': typeof ActivityActivityRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/venues': typeof VendorVenuesRoute
  '/venue/$venueId': typeof VenueVenueIdRouteWithChildren
  '/venue/$venueId/courts': typeof VenueVenueIdCourtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/bookings-received'
    | '/confirmation'
    | '/favorites'
    | '/login'
    | '/profile'
    | '/signup'
    | '/summary'
    | '/vendor'
    | '/activity/$activity'
    | '/vendor/dashboard'
    | '/vendor/venues'
    | '/venue/$venueId'
    | '/venue/$venueId/courts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/bookings-received'
    | '/confirmation'
    | '/favorites'
    | '/login'
    | '/profile'
    | '/signup'
    | '/summary'
    | '/vendor'
    | '/activity/$activity'
    | '/vendor/dashboard'
    | '/vendor/venues'
    | '/venue/$venueId'
    | '/venue/$venueId/courts'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/bookings-received'
    | '/confirmation'
    | '/favorites'
    | '/login'
    | '/profile'
    | '/signup'
    | '/summary'
    | '/vendor'
    | '/activity/$activity'
    | '/vendor/dashboard'
    | '/vendor/venues'
    | '/venue/$venueId'
    | '/venue/$venueId/courts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  BookingsReceivedRoute: typeof BookingsReceivedRoute
  ConfirmationRoute: typeof ConfirmationRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SummaryRoute: typeof SummaryRoute
  VendorRoute: typeof VendorRouteWithChildren
  ActivityActivityRoute: typeof ActivityActivityRoute
  VenueVenueIdRoute: typeof VenueVenueIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings-received': {
      id: '/bookings-received'
      path: '/bookings-received'
      fullPath: '/bookings-received'
      preLoaderRoute: typeof BookingsReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$venueId': {
      id: '/venue/$venueId'
      path: '/venue/$venueId'
      fullPath: '/venue/$venueId'
      preLoaderRoute: typeof VenueVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/venues': {
      id: '/vendor/venues'
      path: '/venues'
      fullPath: '/vendor/venues'
      preLoaderRoute: typeof VendorVenuesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof VendorRoute
    }
    '/activity/$activity': {
      id: '/activity/$activity'
      path: '/activity/$activity'
      fullPath: '/activity/$activity'
      preLoaderRoute: typeof ActivityActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$venueId/courts': {
      id: '/venue/$venueId/courts'
      path: '/courts'
      fullPath: '/venue/$venueId/courts'
      preLoaderRoute: typeof VenueVenueIdCourtsRouteImport
      parentRoute: typeof VenueVenueIdRoute
    }
  }
}

interface VendorRouteChildren {
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorVenuesRoute: typeof VendorVenuesRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorDashboardRoute: VendorDashboardRoute,
  VendorVenuesRoute: VendorVenuesRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

interface VenueVenueIdRouteChildren {
  VenueVenueIdCourtsRoute: typeof VenueVenueIdCourtsRoute
}

const VenueVenueIdRouteChildren: VenueVenueIdRouteChildren = {
  VenueVenueIdCourtsRoute: VenueVenueIdCourtsRoute,
}

const VenueVenueIdRouteWithChildren = VenueVenueIdRoute._addFileChildren(
  VenueVenueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  BookingsReceivedRoute: BookingsReceivedRoute,
  ConfirmationRoute: ConfirmationRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SummaryRoute: SummaryRoute,
  VendorRoute: VendorRouteWithChildren,
  ActivityActivityRoute: ActivityActivityRoute,
  VenueVenueIdRoute: VenueVenueIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
